### ISSUE TITLE
Enabling the wiki

### ISSUE THREAD

**Issue by csnewman** [AeonLucid/POGOProtos#130] opened 2016-08-03 13:56 UTC
Is it worth enabling the Wiki on this repo and adding extra network details that don’t belong inside of the repo really. Like having a page about how the login procedure works and that explains that you will need to use the auth info in requests later on etc? Information also about the order of the initial RPC calls in the original client could also be added so people know how to emulate the original client and make it look like it is the real client. This is information that is important to people implementing their own APIs for example but there is no central location for this as far as I can see. My suggestion is that the Wiki could be used.

**Comment by rubenvereecken** [comment] 2016-08-04 08:01
Actually this is exactly what protobufs are for. They're meant to be more comment than actual content in order to explain the semantics. It's normal to have over 5 lines for a single field/message. I say let's dump it in the protobuf definitions, as intended.

_Then_ I'll consider having Wiki pages to maybe elaborate on some obscure details, but they really should be a last resort.

**Comment by csnewman** [comment] 2016-08-04 09:43
But where would you put information about the inital logging in procedure like PTC and google in this setup? They are really important stages that ought to be documented somewhere.

**Comment by vmarchaud** [comment] 2016-08-05 09:29
If someone want to make a PR, feel free to make one. @rubenvereecken is right, this repo is mainly for protos, not a tutorial on how to implement the network protocol from scratch.

**Comment by rubenvereecken** [comment] 2016-08-05 09:41
@vmarchaud not entirely what I wanted to get across. A lot of details _can_ go in the protobuf definitions, they can contain a lot of semantics. Protobufs do in fact describe a network protocol.

@csnewman you raise a good point where login is concerned, as this is before the protocol gets used. I guess a wiki would be a good place to describe just that, but it would be a bit forlorn, all alone. I would consider the wiki, just for this. @AeonLucid ?

**Comment by rubenvereecken** [comment] 2016-08-05 10:02
https://github.com/AeonLucid/POGOProtos/wiki/Login-Procedure

**Comment by AeonLucid** [comment] 2016-11-06 13:49
Closing this issue.

**Closed as completed by AeonLucid** 2016-11-06 13:49 UTC
