### ISSUE TITLE
StartGymBattleMessage

### ISSUE THREAD

**Issue by chrisoro** [AeonLucid/POGOProtos#120] opened 2016-07-31 21:24 UTC
I'm using the C# api and basically

PostProtoPayload<Request, StartGymBattleResponse>(RequestType.StartGymBattle, message)

is always returning an empty reponse.

**Comment by krzys-h** [comment] 2016-07-31 21:33
1) Make sure the API has this recent commit merged in - 333e54707ca221324c6b9eedb6a7bc2fcae02270
2) Make sure the API is handling status code 53 correctly (I've seen a few that do it only on initial login sequence and fail to process it when it comes from StartGymBattle)

**Comment by jamie2016-1** [comment] 2016-08-12 20:20
@krzys-h can you explain what you mean by handling status code 53? The response type does not have such a field and what fields are there are all unset or null?

Do you mean another response or? Maybe post some snippet code of the c sharp example.

Right now Im having the same issue, it barely ever returns anything other than nothing.

**Comment by krzys-h** [comment] 2016-08-12 20:37
Status code is set in the main [ResponseEnvelope](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Envelopes/ResponseEnvelope.proto#L8) object (the one that holds all individual RPC responses).

If it returns a status_code = 53, it means that you need to change the endpoint that you send all requests to. New endpoint is given in api_url field in the same object - there should be some related code in your API already as it needs to do it always when starting a new session to get the initial URL. You also need to retry the current request after the change.

I have not worked with C# API so I don't know how it's done there. I can give you Python code if it helps in any way - https://github.com/tejado/pgoapi/pull/161

**Comment by krzys-h** [comment] 2016-08-12 20:41
Another Python implementation of the same thing - https://github.com/keyphact/pgoapi/commit/632b7df96d917a323bcd4f386372d2614c04c908#diff-d362e6a32df73ee17a3ddf5ecc2bd150R119

**Comment by krzys-h** [comment] 2016-08-12 20:46
I'm not sure if this is the API you are using, but it seems to be implemented: https://github.com/AeonLucid/POGOLib/blob/master/POGOLib/Net/RPCClient.cs#L364-L371

**Comment by jamie2016-1** [comment] 2016-08-12 21:02
Hi yes I am using https://github.com/AeonLucid/POGOProtos. Also the responseEnvelope status code is 2 for the StartGymBattle but still the actual resppnse from the StartGymBattle service is empty?

**Comment by krzys-h** [comment] 2016-08-12 21:14
Could it possibly be that Unknown6 is missing?
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by jamie2016-1** [comment] 2016-08-12 21:40
no thats in the message. I can send you message if you want, maybe you see something?

**Comment by jamie2016-1** [comment] 2016-08-12 22:03
@krzys-h I just send you an email with the message within, If you could maybe have a look and see if you see anything blantantly incorrect there. Thanks again.

**Comment by jamie2016-1** [comment] 2016-08-13 19:44
Just as an update this is still the case with the C Sharp API. Response is empty, even though the Response Envelope is ok. 

Would be cool if someone could look into it, try and reproduce it themselves etc. I have done numerous tests. 

I am passing in the GymId from the GetGymDetails, the Defending Pokemon is the First Member pokemon from the GetGymDetails, and I pass in 6 pokemon to attack if team != my team is different or 1 if the teams are the same.

**Comment by blackms** [comment] 2016-09-12 16:25
Guys the problem stil persist, someone has managed to fix it?

**Comment by blackms** [comment] 2016-09-12 16:32
I still receiving a lot of times this response:

`{{ "statusCode": 3, "requestId": "841973700021381376", "unknown6": [ { "responseType": 6, "unknown2": { "unknown1": "1" } } ], "returns": [ "" ] }}`

The strange thing is that I don't get it everytime but sometimes it works.

**Comment by AeonLucid** [comment] 2016-11-06 13:46
Closing this issue, let me know if this is still relevant.

**Closed as completed by AeonLucid** 2016-11-06 13:46 UTC
